---
- name: Download file from internet
  get_url:
    url: http://download.jboss.org/wildfly/12.0.0.Final/wildfly-12.0.0.Final.zip
    dest: /home/giovanni/Downloads/wildfly-12.0.0.Final.zip

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /home/giovanni/Downloads/wildfly-12.0.0.Final.zip
    dest: /home/giovanni/Documents
    remote_src: yes
